# Generated by Django 4.0.6 on 2022-07-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_admodel_options_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.categorymodel'),
        ),
        migrations.AlterField(
            model_name='admodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
    ]
